spring.application.name=Job-Portal

# ========== Database Configuration ==========
spring.datasource.url=jdbc:mysql://localhost:3306/jobPortal?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA / Hibernate Configuration ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ========== Logging ==========
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE


#HARDCODED VALUES

USER_FOUND= Email registered already.
USER_NOT_FOUND = User is not registered.
INVALID_CREDENTIALS= Invalid Credentials.
PROFILE_NOT_FOUND=Profile not found.
INCORRECT_OLD_PASSWORD = Old password is incorrect
NEW_PASS_NOT_SAME_AS_OLD_PASS=New password must be different from old password
OTP_NOT_FOUND=No OTP found for email
INVALID_OTP=Invalid OTP
OTP_EXPIRED=OTP has expired
JOB_NOT_FOUND=Job not found.
JOB_APPLIED_ALREADY=Already Applied to this Job.
APPLICANT_NOT_FOUND=Applicant not found.


# ========== Email Configuration ==========

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikhiltiwarip29@gmail.com
spring.mail.password=rpodbwzqlegfmpjf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


